# Generated by Django 5.0.6 on 2024-07-08 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qure2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='operation10',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='person_contact',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='oraganization',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='qure2.organization'),
            preserve_default=False,
        ),
    ]
