# Generated by Django 5.0.6 on 2024-07-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qure2', '0002_remove_patientrecord_operation10_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientrecord',
            old_name='oraganization',
            new_name='Organization',
        ),
    ]
