from django.urls import path
from .views import *

urlpatterns = [
    path('person/', PersonListCreateView.as_view(), name='person-list-create'),
    path('person/<int:pk>/', PersonDetailView.as_view(), name='person-detail'),
    path('person/all/', AllPersonListView.as_view(), name='all-person-list'),  
    path('person/delete/<int:pk>/', PersonDetailView.as_view(), name='person-delete'), 
    path('person/update/<int:pk>/', PersonUpdateView.as_view(), name='person-update'), 
    path('pratician/', PraticianListCreateView.as_view(), name='pratician-list-create'),
    path('pratician/<int:pk>/', PraticianDetailView.as_view(), name='pratician-detail'),
    path('pratician/all/', AllPraticianListView.as_view(), name='all-pratician-list'),  
    path('pratician/delete/<int:pk>/', PraticianDeleteView.as_view(), name='pratician-delete'), 
    path('pratician/update/<int:pk>/', PraticianUpdateView.as_view(), name='pratician-update'), 
    path('organization/', OrganizationListCreateView.as_view(), name='organization-list-create'),
    path('organization/<int:pk>/', OrganizationDetailView.as_view(), name='organization-detail'),
    path('organization/all/', AllOrganizationListView.as_view(), name='all-organization-list'),  
    path('organization/delete/<int:pk>/', OrganizationDeleteView.as_view(), name='organization-delete'), 
    path('organization/update/<int:pk>/', OrganizationUpdateView.as_view(), name='organization-update'),
    path('subcription/', SubcriptionListCreateView.as_view(), name='subcription-list-create'),
    path('subcription/<int:pk>/', SubcriptionDetailView.as_view(), name='subcription-detail'),
    path('subcription/all/', AllSubcriptionListView.as_view(), name='all-subcription-list'),  
    path('subcription/delete/<int:pk>/', SubcriptionDeleteView.as_view(), name='subcription-delete'), 
    path('subcription/update/<int:pk>/', SubcriptionUpdateView.as_view(), name='subcription-update'),
    path('user/', AccountListCreateView.as_view(), name='account-list-create'),
    path('user/<int:pk>/', AccountDetailView.as_view(), name='account-detail'),
    path('user/all/', AllAccountListView.as_view(), name='account-person-list'),  
    path('user/delete/<int:pk>/', AccountDetailView.as_view(), name='account-delete'), 
    path('user/update/<int:pk>/', AccountUpdateView.as_view(), name='account-update'),  
    path('organization/<int:organization_id>/users/', AccountsByOrganizationView.as_view(), name='accounts-by-organization'),
    path('patient/', PatientListCreateView.as_view(), name='patient-list-create'),
    path('patient/<int:pk>/', PatientDetailView.as_view(), name='patient-detail'),
    path('patient/delete/<int:pk>/', PatientDeleteView.as_view(), name='patient-delete'), 
    path('patient/update/<int:pk>/', PatientUpdateView.as_view(), name='patient-update'),
    path('person/search/', PersonSearchByNameView.as_view(), name='patient-search-by-name'),
    path('record/', PatientRecordListCreateView.as_view(), name='patientrecord-list-create'),
    path('record/<int:pk>/', PatientRecordDetailView.as_view(), name='patientrecord-detail'),
    path('transfert/', TransfertListCreateView.as_view(), name='transfert-list-create'),
    path('transfert/<int:pk>/', TransfertDetailView.as_view(), name='transfert-detail'),
    path('transfert/all/', AllTransfertListView.as_view(), name='all-transfert-list'),  
    path('transfert/delete/<int:pk>/', TransfertDetailView.as_view(), name='transfert-delete'), 
    path('transfert/update/<int:pk>/', TransfertUpdateView.as_view(), name='transfert-update'),
    path('practician/<int:practician_id>/consulations/', ConsultationByPracticianView.as_view(), name='consultation-by-practician'),
    path('patient/<int:patient_id>/consulations/', ConsultationByPatientView.as_view(), name='patient-by-pratician'),
    path('patient/<int:patient_id>/practician/<int:practician_id>/consultation/', ConsultationsByPatientPracticianView.as_view(), name='consultations-by-patient-practician'),
    path('consultation/', ConsultationListCreateView.as_view(), name='consultation-list-create'),
    path('consultation/<int:pk>/', ConsultationDetailView.as_view(), name='consultation-detail'),
    path('examination/', ExaminationListCreateView.as_view(), name='examination-list-create'),
    path('examination/<int:pk>/', ExaminationDetailView.as_view(), name='examination-detail'),
    path('prescription/', PrescriptionListCreateView.as_view(), name='prescription-list-create'),
    path('prescription/<int:pk>/', PrescriptionDetailView.as_view(), name='prescription-detail'),
    path('consultation/<int:pk>/', ConsultationDetailView.as_view(), name='consultation-detail'),
    
]